{
domain_name shell : appdomain,netdomain,mlstrustedsubject;
domain_trans runas;
domain_trans adbd /system/bin/sh;
domain_trans zygote;
  
  allow /data/anr/** r,w,s,x;
  allow /data/app/** r,w,s,x;
  allow /data/bootchart/** r,w,s,x;
  allow /data/local/tmp/** r,w,s,x;
  allow /data/misc/logd/** r,w,s,x;
  allow /dev/console r,w,x,s;
  allow /dev/input(/.*) r,w,s,x;
  allow /dev/kgsl r,w,x,s;
  allow /dev/kgsl-3d0 r,w,x,s;
  allow /dev/pts r,w,x,s;
  allow /dev/pvrsrvkm r,w,x,s;
  allow /dev/socket/dumpstate r,w,s;
  allow /dev/socket/logd r,w,s;
  allow /dev/socket/logdr r,w,s;
  allow /dev/socket/property_service r,w,s;
  allow /dev/tty[0-9]* r,w,x,s;
  allow /mnt/expand/[^/]+/app/** r,w,s,x;
  allow /mnt/expand/[^/]+/local/tmp/** r,w,s,x;
  allow /odm/** r,x,s;
  allow /system/** r,x,s;
  allow /system/bin/app_process32 r,w,x,s;
  allow /system/bin/app_process64 r,w,x,s;
  allow /system/bin/logcat r,w,x,s;
  allow /system/bin/logwrapper r,x,s;
  allow /system/bin/run-as r,w,x,s;
  allow /system/bin/sh r,w,x,s;
  allow /system/bin/toolbox r,w,x,s;
  allow /system/bin/toybox r,w,x,s;
  allow /system/xbin/procrank r,w,x,s;
  allow /system/xbin/simpleperf r,x,s;
  allow /system/xbin/su r,w,x,s;
  allow /vendor/** r,x,s;
  allowbinder keystore c ;
  allowbinder su c ;
  allowbinder surfaceflinger t ;
  allowcom -ipc app_data_file r; #allow shell app_data_file:fifo_file { rename setattr read lock create getattr write ioctl unlink open append };
  allowcom -ipc app_data_file w; #allow shell app_data_file:fifo_file { rename setattr read lock create getattr write ioctl unlink open append };
  allowcom -ipc dumpstate w; #allow shell dumpstate:unix_stream_socket connectto;
  allowcom -ipc init w; #allow shell init:unix_stream_socket connectto;
  allowcom -ipc logd w; #allow shell logd:unix_stream_socket connectto;
  allowcom -ipc shell r; #allow shell shell:fifo_file { read lock getattr write ioctl open append };
  allowcom -ipc shell r; #allow shell shell:unix_dgram_socket { setopt setattr read lock create sendto getattr write ioctl connect shutdown bind getopt append };
  allowcom -ipc shell r; #allow shell shell:unix_stream_socket { connectto setopt setattr read lock create getattr accept write ioctl connect shutdown bind getopt append listen };
  allowcom -ipc shell w; #allow shell shell:fifo_file { read lock getattr write ioctl open append };
  allowcom -ipc shell w; #allow shell shell:unix_dgram_socket { setopt setattr read lock create sendto getattr write ioctl connect shutdown bind getopt append };
  allowcom -ipc shell w; #allow shell shell:unix_stream_socket { connectto setopt setattr read lock create getattr accept write ioctl connect shutdown bind getopt append listen };
  allowcom -sig adbd c; #allow shell adbd:process sigchld;
  allowcom -sig init c; #allow shell init:process sigchld;
  allowcom -sig shell c; #allow shell shell:process { fork getsession sigkill sigchld setpgid setsched signal getattr setcap sigstop execmem getcap getpgid ptrace signull setrlimit getsched };
  allowcom -sig shell k; #allow shell shell:process { fork getsession sigkill sigchld setpgid setsched signal getattr setcap sigstop execmem getcap getpgid ptrace signull setrlimit getsched };
  allowcom -sig shell n; #allow shell shell:process { fork getsession sigkill sigchld setpgid setsched signal getattr setcap sigstop execmem getcap getpgid ptrace signull setrlimit getsched };
  allowcom -sig shell o; #allow shell shell:process { fork getsession sigkill sigchld setpgid setsched signal getattr setcap sigstop execmem getcap getpgid ptrace signull setrlimit getsched };
  allowcom -sig shell s; #allow shell shell:process { fork getsession sigkill sigchld setpgid setsched signal getattr setcap sigstop execmem getcap getpgid ptrace signull setrlimit getsched };
  allowdev -pts devpts r;
allowdev -pts devpts w;

  allowdev -root /dev;
  allowks keystore i,g,s ;
  allownet -protocol raw use;
  allowpriv execmem;
  allowpriv getsecattr;
  allowpriv getsecurity;
  allowpriv klog_read;
  allowpriv netlink;
  allowpriv ptrace;
  allowpriv relabel;
  allowpriv setsecurity;
  allowprop ctl.dumpstate ;
  allowprop debug. ;
  allowprop log. ;
  allowprop security.perf_harden ;
  allowprop service.adb.root ;
  allowprop service.adb.tcp.port ;
  allowprop sys.powerctl ;
  allowsvc * f ;
  allowsvc -name servicemanager l ;
  allowsvc -name system_app_service f ;
  allowsvc DockObserver f ;
  allowsvc SurfaceFlinger f ;
  allowsvc accessibility f ;
  allowsvc account f ;
  allowsvc activity f ;
  allowsvc alarm f ;
  allowsvc android.hardware.fingerprint.IFingerprintDaemon f ;
  allowsvc android.security.keystore f ;
  allowsvc appops f ;
  allowsvc appwidget f ;
  allowsvc assetatlas f ;
  allowsvc audio f ;
  allowsvc backup f ;
  allowsvc battery f ;
  allowsvc batteryproperties f ;
  allowsvc batterypropreg f ;
  allowsvc batterystats f ;
  allowsvc bluetooth f ;
  allowsvc bluetooth_manager f ;
  allowsvc carrier_config f ;
  allowsvc clipboard f ;
  allowsvc com.android.net.IProxyService f ;
  allowsvc common_time.clock f ;
  allowsvc common_time.config f ;
  allowsvc commontime_management f ;
  allowsvc connectivity f ;
  allowsvc consumer_ir f ;
  allowsvc content f ;
  allowsvc country_detector f ;
  allowsvc cpuinfo f ;
  allowsvc dbinfo f ;
  allowsvc device_policy f ;
  allowsvc deviceidle f ;
  allowsvc devicestoragemonitor f ;
  allowsvc diskstats f ;
  allowsvc display f ;
  allowsvc display.qservice f ;
  allowsvc dreams f ;
  allowsvc drm.drmManager f ;
  allowsvc dropbox f ;
  allowsvc ethernet f ;
  allowsvc fingerprint f ;
  allowsvc gfxinfo f ;
  allowsvc graphicsstats f ;
  allowsvc hardware f ;
  allowsvc hdmi_control f ;
  allowsvc imms f ;
  allowsvc ims f ;
  allowsvc input f ;
  allowsvc input_method f ;
  allowsvc inputflinger f ;
  allowsvc iphonesubinfo f ;
  allowsvc iphonesubinfo2 f ;
  allowsvc iphonesubinfo_msim f ;
  allowsvc isms f ;
  allowsvc isms2 f ;
  allowsvc isms_msim f ;
  allowsvc isub f ;
  allowsvc jobscheduler f ;
  allowsvc launcherapps f ;
  allowsvc location f ;
  allowsvc lock_settings f ;
  allowsvc media.audio_flinger f ;
  allowsvc media.audio_policy f ;
  allowsvc media.camera f ;
  allowsvc media.camera.proxy f ;
  allowsvc media.log f ;
  allowsvc media.player f ;
  allowsvc media.radio f ;
  allowsvc media.resource_manager f ;
  allowsvc media.sound_trigger_hw f ;
  allowsvc media_projection f ;
  allowsvc media_router f ;
  allowsvc media_session f ;
  allowsvc meminfo f ;
  allowsvc midi f ;
  allowsvc mount f ;
  allowsvc netpolicy f ;
  allowsvc netstats f ;
  allowsvc network_management f ;
  allowsvc network_score f ;
  allowsvc nfc f ;
  allowsvc notification f ;
  allowsvc package f ;
  allowsvc permission f ;
  allowsvc persistent_data_block f ;
  allowsvc phone f ;
  allowsvc phone1 f ;
  allowsvc phone2 f ;
  allowsvc phone_msim f ;
  allowsvc power f ;
  allowsvc print f ;
  allowsvc processinfo f ;
  allowsvc procstats f ;
  allowsvc radio.phone f ;
  allowsvc radio.phonesubinfo f ;
  allowsvc radio.sms f ;
  allowsvc restrictions f ;
  allowsvc rttmanager f ;
  allowsvc samplingprofiler f ;
  allowsvc scheduling_policy f ;
  allowsvc search f ;
  allowsvc sensorservice f ;
  allowsvc serial f ;
  allowsvc servicediscovery f ;
  allowsvc simphonebook f ;
  allowsvc simphonebook2 f ;
  allowsvc simphonebook_msim f ;
  allowsvc sip f ;
  allowsvc statusbar f ;
  allowsvc task f ;
  allowsvc telecom f ;
  allowsvc telephony.registry f ;
  allowsvc textservices f ;
  allowsvc trust f ;
  allowsvc tv_input f ;
  allowsvc uimode f ;
  allowsvc updatelock f ;
  allowsvc usagestats f ;
  allowsvc usb f ;
  allowsvc user f ;
  allowsvc vibrator f ;
  allowsvc voiceinteraction f ;
  allowsvc wallpaper f ;
  allowsvc webviewupdate f ;
  allowsvc wifi f ;
  allowsvc wifip2p f ;
  allowsvc wifiscanner f ;
  allowsvc window f ;
  allowtmp -fs tmpfs -name auto r,w;
  inline "allow shell app_data_file:dir { rename search setattr read create reparent getattr write ioctl rmdir remove_name open add_name };" #path_list: 
  inline "allow shell app_data_file:file { rename setattr read lock create getattr write ioctl unlink open append };" #path_list: 
  inline "allow shell app_data_file:lnk_file { rename setattr read lock create getattr write ioctl unlink open append };" #path_list: 
  inline "allow shell app_data_file:sock_file { rename setattr read lock create getattr write ioctl unlink open append };" #path_list: 
  inline "allow shell debugfs:file { read lock ioctl open getattr };" #path_list: 
  inline "allow shell domain:dir { read getattr open search };" #path_list: 
  inline "allow shell domain:file { read getattr open };" #path_list: 
  inline "allow shell domain:lnk_file { read getattr open };" #path_list: 
  inline "allow shell procrank:process transition;"
  inline "allow shell pstorefs:dir search;" #path_list: 
  inline "allow shell pstorefs:file { read lock ioctl open getattr };" #path_list: 
  inline "allow shell runas:process transition;"
  inline "allow shell shell:dir { read search ioctl open getattr };" #path_list: 
  inline "allow shell shell:file { read lock getattr write ioctl open append };" #path_list: 
  inline "allow shell shell:lnk_file { read lock ioctl open getattr };" #path_list: 
  inline "allow shell su:process transition;"
}

